version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda-petshop
      MYSQL_USER: api
      MYSQL_PASSWORD: api
  mysql-workbench:
    depends_on:
      - db
    image: ghcr.io/linuxserver/mysql-workbench
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=America/Fortaleza
    volumes:
      - workbench_conf:/conf
    ports:
      - "3000:3000"
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
volumes:
  db_data: {}
  workbench_conf: {}
