version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: agenda-petshop
      MYSQL_USER: api
      MYSQL_PASSWORD: api
  adminer:
    depends_on:
      - db
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
volumes:
  db_data: {}